# Generated by Django 3.2.5 on 2021-11-09 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='profile_pi',
            new_name='profile_pic',
        ),
    ]
